healthnet/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #message system
    url(r'^messages/', include('postman.urls')),

    # url(r'^blog/', include('blog.urls')),
    url(r'^index', 'healthnet.views.index', name='index'),
    
    url(r'^admin/', include(admin.site.urls), name='admin-site'),
    #users
    url(r'^users/', include('users.urls')),
    #
    url(r'^account/', include('accounts.urls')),
    url(r'^medicalinfomation/', include('medicalinfo.urls'), name='med-info'),

    
    url(r'^contactus/$', 'healthnet.views.contactus', name='contactus'),
    url(r'^statistic/$', 'healthnet.views.statistic', name='statistic-home'),

	url(r'^$', 'healthnet.views.home', name='home'),

    url(r'^schedule/', include('scheduling.urls')),

)

handler403 = 'healthnet.views.http403'
handler404 = 'healthnet.views.http404'

medicalinfo/urls.py
from django.conf.urls import patterns, url
from medicalinfo import views

urlpatterns = patterns('',
	url(r'^$', views.index),
	#url(r'^register/$', views.patient_register, name='patient-register'),

	url(r'^(?P<ref_id>[\w]+)/initializing/$', views.medinfo_init,name='med-info-init'),
	url(r'^(?P<ref_id>[\w]+)/new-case/$', views.case_init,name='case-init'),
	url(r'^(?P<ref_id>[\w]+)/cases/(?P<case_id>[\d]+)/new-prescription/$', views.case_update_prescription,name='case-update-prescription'),
	url(r'^(?P<ref_id>[\w]+)/cases/(?P<case_id>[\d]+)/update/$', views.case_update,name='case-update'),

	url(r'^(?P<ref_id>[\w]+)/cases/(?P<case_id>[\d]+)$', views.case_detail_view,name='case-detail-view'),

	url(r'^(?P<ref_id>[\w]+)/cases/$', views.case_list_view,name='case-list-view'),

	
	#url(r'^(?P<ref_id>[\w]+)/new-case/$', views.diagnosis_init,name='case-init'),


	url(r'^(?P<ref_id>[\w]+)/$', views.medinfo_view,name='med-info-detail'),
	#url(r'^(?P<ref_id>[\w]+)/update/$', views.userprofile_update, name='userprofile-update'),

)

schedule/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import DeleteEventView

urlpatterns = patterns(
    '',
    # urls for Calendars
    url(r'^calendar/$',
        ListView.as_view(queryset=Calendar.objects.all(),
                         template_name='schedule/calendar_list.html'),
        name="calendar_list"),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="year_calendar",
        kwargs={'periods': [Year], 'template_name': 'schedule/calendar_year.html'}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="tri_month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_tri_month.html'}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="compact_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_compact_month.html'}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="month_calendar",
        kwargs={'periods': [Month], 'template_name': 'schedule/calendar_month.html'}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="week_calendar",
        kwargs={'periods': [Week], 'template_name': 'schedule/calendar_week.html'}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar_by_periods',
        name="day_calendar",
        kwargs={'periods': [Day], 'template_name': 'schedule/calendar_day.html'}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.calendar',
        name="calendar_home",
        ),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        'schedule.views.create_or_edit_event',
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        'schedule.views.create_or_edit_event',
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        'schedule.views.event',
        name="event"),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name="delete_event"),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence"),

    #urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.occurrence',
        name="occurrence_by_date"),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.cancel_occurrence',
        name="cancel_occurrence_by_date"),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        'schedule.views.edit_occurrence',
        name="edit_occurrence_by_date"),

    #feed urls
    url(r'^feed/calendar/upcoming/(.*)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),
    #api urls
    url(r'^api/occurrences', 'schedule.views.api_occurrences', name='api_occurences'),

    url(r'^$', ListView.as_view(queryset=Calendar.objects.all()), name='schedule'),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views 
urlpatterns = patterns('',
	url(r'^$', views.index),

)

medicalinfo/models.py
from django.db import models
from users.models import Patient, Doctor, Nurse, UserProfile
from django.contrib.auth.models import User
from localflavor.us.models import USStateField, USZipCodeField, USSocialSecurityNumberField, PhoneNumberField
from django.core.urlresolvers import reverse
#to track model 
from simple_history.models import HistoricalRecords


#===========================================================================
#===========================================================================
#Each patient will have one medinfo instance, this contains 
#basic medinfo such as history, allergies, emergency contact and 
#insurance information
#===========================================================================
#===========================================================================

class MedicalInformation(models.Model):
	history = HistoricalRecords()
	patient = models.OneToOneField(Patient, primary_key=True, verbose_name='Patient')
	initialized = models.BooleanField(default=False)
	fName = models.CharField(max_length=40, verbose_name ="First Name")
	lName = models.CharField(max_length=40, verbose_name ="Last Name",)
	mName = models.CharField(max_length=40, verbose_name ="Middle Name", blank=True )

	class Meta:
		permissions = (
			("init_medinfo", "can initialize med-info"),
			("read_medinfo", "can view med-info"),
			("init_case", "can init diagnosis"),
		)

	@classmethod
	def create(info, patient):
		new_info = info(patient=patient)
		return new_info
	def __str__(self):
		return self.patient.patient.username + "medinfo"

#===========================================================================
#===========================================================================
#Link to medinfo
#
#===========================================================================
#===========================================================================

class ChronicMedicalProblems(models.Model):
	history = HistoricalRecords()
	medinfo = models.OneToOneField(MedicalInformation, verbose_name="Med-info", primary_key=True)
	high_blood = models.BooleanField(default=False, verbose_name="High Blood Pressure")
	heart = models.BooleanField(default=False, verbose_name="Heart Disease")
	diabete = models.BooleanField(default=False, verbose_name="Diabetes")
	stroke = models.BooleanField(default=False, verbose_name="Stroke")
	cancer = models.BooleanField(default=False, verbose_name="Cancer")
	thyroid = models.BooleanField(default=False, verbose_name="Thyroid")
	asthma = models.BooleanField(default=False, verbose_name="Asthma")
	other = models.CharField(max_length=200, blank=True, verbose_name="Others")

	def __str__(self):
		return self.medinfo.patient.patient.username

#===========================================================================
#===========================================================================
#link to medinfo
#
#===========================================================================
#===========================================================================

class Allergen(models.Model):
	history = HistoricalRecords()
	medinfo = models.OneToOneField(MedicalInformation, verbose_name="Med-info", primary_key=True)
	food = models.BooleanField(default=False, verbose_name="Food Allergic")
	food_allegies = models.CharField(max_length=200, blank=True, verbose_name="Food")
	drug = models.BooleanField(default=False, verbose_name="Drug Allergic")
	drug_allegies = models.CharField(max_length=200, blank=True, verbose_name="Drugs")
	environmental = models.BooleanField(default=False, verbose_name="Environmental Allergic")
	environmental_allegies = models.CharField(max_length=200, blank=True, verbose_name="Environment")

	def __str__(self):
		return self.medinfo.patient.patient.username

#===========================================================================
#===========================================================================
#Link to medinfo
#
#===========================================================================
#===========================================================================

class EmergencyContact(models.Model):
	history = HistoricalRecords()
	patient = models.OneToOneField(Patient, primary_key=True)
	name = models.CharField(max_length=100, blank=True, verbose_name="Emergency Contact Name")
	phone = PhoneNumberField(blank=True, verbose_name="Phone")
	relationship = models.CharField(max_length=20, blank=True, verbose_name="relationship to patient")

	def __str__(self):
		return self.patient.patient.username

#===========================================================================
#===========================================================================
#Link to med info
#
#===========================================================================
#===========================================================================

class InsuranceInformation(models.Model):
	INSURANCE_CHOICES = (
        ('B', 'Blue Choice Options'),
        ('U', 'United Healthcare'),
        ('M', 'Medicaid'),
        ('N', 'None'),
        )

	history = HistoricalRecords()
	patient = models.OneToOneField(Patient, primary_key=True, verbose_name='Related Patient')
	policy_holder = models.CharField(max_length=100, verbose_name="Policy Holder", blank=True)
	carrier = models.CharField(max_length=1, verbose_name="Insurance Carrier", choices=INSURANCE_CHOICES, default='N')
	policy_number = models.CharField(max_length=10, verbose_name="Policy Number", blank=True)

	def __str__(self):
		return self.patient.patient.username

#===========================================================================
#===========================================================================
#
#When a patient have a problem, a case will be created and will be used by doctor to 
#diagnose, update test result, and prescription
#
#===========================================================================
#===========================================================================

class Case(models.Model):
	CASE_STATUS_CHOICES = (
        ('A', 'Active'),
        ('C', 'Closed'),
        ('N', 'New'),
        )
	LAST_ACTION_CHOIES = (
		('N', 'Created'),
		('D', 'Updated'),
		('P', 'New Prescription Updated'),
		)

	history = HistoricalRecords()
	medinfo = models.ForeignKey(MedicalInformation, verbose_name="Med-info")
	status = models.CharField(max_length=1, choices=CASE_STATUS_CHOICES, verbose_name='Case Status', default='N')
	problem = models.CharField(max_length=200, verbose_name='Problem/Concern')
	diagnosis = models.CharField(max_length=200, verbose_name='Diagnosis', default='None')
	test_result = models.CharField(max_length=200, verbose_name='Test Result', default='None')
	last_action = models.CharField(max_length=1, choices=LAST_ACTION_CHOIES, verbose_name='Last action', default='N')
	created = models.DateField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.problem


#===========================================================================
#===========================================================================
#Each case will have 0-* presciptions 
#
#===========================================================================
#===========================================================================

class Prescription(models.Model):
	history = HistoricalRecords()
	case = models.ForeignKey(Case, verbose_name="Related Case")
	drug = models.CharField(max_length=200, verbose_name="Drug")
	instruction = models. CharField(max_length=200, verbose_name="Instruction")
	refill = models.PositiveSmallIntegerField(default=0, verbose_name="Refill")
	created = models.DateField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.case + " " + self.drug

medicalinfo/templates/medicalinfo/medinfo_case_detail_view_form.html
{%extends 'base.html' %}

{% block content %}



<div class="container">

<div class="page-header">
        <h1>Case Detail <small>Patient: {{patient}}</small></h1>
 </div>

    <form action="" method="POST">{%csrf_token%}
      
    <div class="row">
    <div class="col-md-6">

        {{form1.as_p}}
    </div>
    <div class="col-md-6">
    	<h3>Prescription</h3>
        <div clsas="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>
    {%if user.employee.doctor %}
        <a class="btn btn-primary" href="{%url 'case-update-prescription' ref_id=ref_id case_id=case_id%}">New Precription</a>
        <a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id %}">Back</a>
   

     {%endif%}
       
    </div>

    </div>

    {%if user.employee.doctor %}
    <br>
    <a class="btn btn-primary" href="{%url 'case-update' ref_id=ref_id case_id=case_id%}">Update</a>
    {%endif%}
    <a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id%}">Back</a>

    </form>

<div class="containter"> 
<div id="content">
    <div class='hidden'>
        <h2>Case Report</h2>
        <h3> Patient: {{patient}}</h3>
        <p id="demo"></p>


            <table class="table">
                    <tr>
                        <th>Problem/Concern: {{case.problem}}</th>
                    </tr>
                    <tr>
                        <th>Diagnosis: {{case.diagnosis}}</th>
                    </tr>
                    <tr>
                        <th>Test Result: {{case.test_result}}</th>
                    </tr>
            </table>
                <h3>Prescription</h3>
                    <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>

    </div>

</div> <hr>
<button class="btn btn-primary" id="cmd"><span class="glyphicon glyphicon-floppy-disk"></span> Save as PDF</button>
</form>

</div><!-- /container -->
<script>
document.getElementById("demo").innerHTML = Date();
</script>

{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_case_list_view.html
{%extends 'base.html' %}

{% block content %}


<div class="container">
 <div class="page-header">
	<h1>Cases <small>Patient: {{patient}}</small></h1>

</div>



<nav>
<ul class="pagination">
    <span class="step-links">
        {% if cases.has_previous %}
            <a href="?page={{ cases.previous_page_number }}"><span class="glyphicon glyphicon-arrow-left"></a>
        {% endif %}

        <span class="current">
            Page {{ cases.number }} of {{ cases.paginator.num_pages }}.
        </span>

        {% if cases.has_next %}
            <a href="?page={{ cases.next_page_number }}"><span class="glyphicon glyphicon-arrow-right"></span></a>
        {% endif %}
    </span>
</ul>

</nav>


<table class="table">
<thead>
	<tr>
		<th>Case</th>
		<th>Status*</th>
		<th>Last Action</th>
	</tr>
</thead>
<tbody>
	{%for case in cases%}
	<tr>
		<th> <a href="{% url 'case-detail-view' ref_id=ref_id case_id=case.id %}"> {{case}}</a></th>
		<th>{{case.status}}</th>
		<th>{{case.get_last_action_display}} on {{case.updated}}</th>
	</tr>
{%endfor%}

</tbody>
</table>
    <a class="btn btn-primary" href="{%url 'case-init' ref_id=ref_id%}">New Case Inquiry</a>
    
<p class="help-block">*Case Status: N=New, A=Active, C=Closed</p>
</div>
{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_case_update_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      
    <div class="row">
    <div class="col-md-6">
    <h3>Case Detail</h3>

        {{form1.as_p}}
    </div>

    <div class="col-md-6">
    	<h3>Prescription</h3>
      <div clsas="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>

    </div>

    </div>

    {%if user.employee.doctor %}
    <br>
    <button class="btn btn-primary" type="submit">Update</button>
    <a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id %}">Back</a>
   

    {%endif%}
 
    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_case_update_prescription_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      
    <div class="row">
    <div class="col-md-6">
    <h3>Case Detail</h3>

        {{form1.as_p}}
    </div>

    <div class="col-md-6">
    	<h3>Prescription</h3>
      <div clsas="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>

        {{form2.as_p}}
    {%if user.employee.doctor %}
    <br>
    <button class="btn btn-primary" type="submit">Update</button>
    <a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id %}">Cancel</a>
   

    {%endif%}
 

    </div>

    </div>

    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_diagnosis_init_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      
    <h2>New Diagnosis</h2>
    <div class="row">
    <div class="col-md-6">
        {{form1.as_p}}
    </div>
    </div>


    <button class="btn btn-primary" type="submit">Submit</button>
 
    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_init_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">
<div class="page-header">
  <h1>Medical Information Initialization</small></small></h1>
</div>

    <form action="" method="POST">{%csrf_token%}
      
     <div class="row">
    <div class="col-md-6">
        <div class="col-md-8">
        {{form1.as_p}}
        </div>
    </div>
    </div>

    <div class="row"> 
    <div class="col-md-6">
        <h4>Emergency Contact</h4><hr>
        <div class="col-md-8">
        {{form3.as_p}}
        </div>    
    </div>
    <div class="col-md-6">
        <h4>Insurance Information</h4><hr>
        <div class="col-md-8">
        {{form4.as_p}}
        </div>
    </div>
    </div>


    <div class="row">
    <div class="col-md-6">
    <h4>Chronical Problem History</h4><hr>
    <table class="table">
        <tr>
            <td>
                {% for field in form2|slice:":4" %}
                <div class="text-right">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
            <td>
                {% for field in form2|slice:"4:" %}
                <div class="text-left">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
        </tr>
    </table>
     </div>

     <div class="col-md-6">
     <h4>Allergens</h4><hr>
        <div class="col-md-8">
        {{form5.as_p}}
        </div>

     </div>


     </div>
    <button class="btn btn-primary" type="submit">Submit</button>
 
    </form>

    </div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_new_case_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      <div class="page-header">
        <h1>New Case Inquiry</h1>
       </div>

    <div class="row">
    <div class="col-md-6">
        {{form1.as_p}}
    </div>
    </div>


    <button class="btn btn-primary" type="submit">Submit</button>
 	<a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id%}">Back</a>
    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_view_form.html
{%extends 'base.html' %}

{% block content %}
        <div class="container">

      <form action="" method="POST">{%csrf_token%}
      <div class="page-header">
        <h1>Medical Information</h1>
        </div>

    <div class="row">
    <div class="col-md-6">
        {{form1.as_p}}
    </div>
    <div class="col-md-6">
    <a class="btn btn-primary" href="{%url 'case-list-view' ref_id=ref_id%}">View Cases</a>
    <a class="btn btn-primary" href="{%url 'case-init' ref_id=ref_id%}">New Case Inquiry</a>
 {%if user.patient.is_active %}
<br>    
<br> 
 <a class="btn btn-default" href="{{user.patient.get_write_to_doc_url}}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Doctor</a>
 <a class="btn btn-default" href="{{user.patient.get_write_to_nurse_url}}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Nurse</a>

 {%endif%}


    </div>
    </div>

    <div class="row">
    <div class="col-md-6">
        <h4>Emergency Contact</h4><hr>
        {{form3.as_p}}
    </div>
    <div class="col-md-6">
        <h4>Insurance</h4><hr>
        {{form4.as_p}}
    </div>
    </div>


    <div class="row">
    <div class="col-md-6">
    <h4>Chronical Problem History</h4><hr>
    <table class="table">
        <tr>
            <td>
                {% for field in form2|slice:":4" %}
                <div class="text-right">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
            <td>
                {% for field in form2|slice:"4:" %}
                <div class="text-left">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
        </tr>
    </table>
     </div>

     <div class="col-md-6">
     <h4>Allergens</h4><hr>
     {{form5.as_p}}
     </div>
     </div>
         <button class="btn btn-primary" type="submit">Update</button>
 
</form>

    </div> <!-- /container -->


{% endblock %}